name: Deploy Python Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Make startup script executable
        run: |
          chmod +x startup.sh
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_APP_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-BCL-app'
          package: .
          startup-command: '/bin/bash startup.sh'
          
      - name: Show Deployment URL
        run: |
          echo "Die App wurde deployed und ist verfügbar unter: https://app-BCL-app.azurewebsites.net" 