name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # 1) Deploy main.bicep
      - name: Deploy basic infrastructure with main.bicep file
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infrastructure/main.bicep
          failOnStdErr: false

      # 2) Deploy aisearch.bicep
      - name: Deploy aisearch.bicep
        id: searchDeploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infrastructure/aisearch.bicep
          parameters: |
            webAppPrincipalId=${{ steps.deploy.outputs.webAppManagedIdentityPrincipalId }}        


      # Beispiel für Verwendung des Outputs im nächsten Step
      #- name: Show Principal ID
      #  run: |
      #    echo "Die App ServicePrincipal ID ist: ${{ steps.deploy.outputs.webAppManagedIdentityPrincipalId }}"
